### ISSUE TITLE
作ったmodelをsimulationで動かす

### ISSUE THREAD

**Issue by 0num4** [0num4/kanachan#8]
## わかっていること
* docker上はhydraを使ってないバージョン(local(gitのmaster)やfeat/developとは結構コードが違う)
* hydraを使ってるバージョンのほうがコードが新しそう

**Comment by 0num4** [comment]
.devcontainerのpostcreate.shの最後のほう
```
# Build kanachan.
mkdir -p /workspaces/kanachan/build
pushd /workspaces/kanachan/build
CC="$HOME/.local/bin/gcc" CXX="$HOME/.local/bin/g++" cmake \
  -DSHANTEN_NUMBER_SOURCE_PATH=/workspaces/shanten-number \
  -DCMAKE_BUILD_TYPE=Release \
  ..
VERBOSE=1 make -j make_trie simulation
mkdir -p "$HOME/.local/share/kanachan"
src/xiangting/make_trie /workspaces/shanten-number "$HOME/.local/share/kanachan"
cp src/simulation/libsimulation.so ../kanachan/simulation/_simulation.so
popd

```

```
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ ls /root/.local/lib/
cmake/                                            libboost_python310-mt-d-x64.so.1.83.0             libboost_stacktrace_backtrace-mt-x64.so           libboost_stacktrace_noop-mt-x64.so.1.83.0
gcc/                                              libboost_python310-mt-x64.so                      libboost_stacktrace_backtrace-mt-x64.so.1.83.0    libmarisa.la
libbacktrace.a                                    libboost_python310-mt-x64.so.1.83.0               libboost_stacktrace_basic-mt-d-x64.so             libmarisa.so
libbacktrace.la                                   libboost_stacktrace_addr2line-mt-d-x64.so         libboost_stacktrace_basic-mt-d-x64.so.1.83.0      libmarisa.so.0
libboost_numpy310-mt-d-x64.so                     libboost_stacktrace_addr2line-mt-d-x64.so.1.83.0  libboost_stacktrace_basic-mt-x64.so               libmarisa.so.0.0.0
libboost_numpy310-mt-d-x64.so.1.83.0              libboost_stacktrace_addr2line-mt-x64.so           libboost_stacktrace_basic-mt-x64.so.1.83.0        pkgconfig/
libboost_numpy310-mt-x64.so                       libboost_stacktrace_addr2line-mt-x64.so.1.83.0    libboost_stacktrace_noop-mt-d-x64.so              
libboost_numpy310-mt-x64.so.1.83.0                libboost_stacktrace_backtrace-mt-d-x64.so         libboost_stacktrace_noop-mt-d-x64.so.1.83.0       
libboost_python310-mt-d-x64.so                    libboost_stacktrace_backtrace-mt-d-x64.so.1.83.0  libboost_stacktrace_noop-mt-x64.so        
```

```
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ ls build/src/simulation/libsimulation.so kanachan/simulation/_simulation.so
build/src/simulation/libsimulation.so  kanachan/simulation/_simulation.so
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ cp build/src/simulation/libsimulation.so kanachan/simulation/_simulation.so
```

`python kanachan/simulation/run.py`

**Comment by 0num4** [comment]
```
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ python kanachan/simulation/run.py 
Traceback (most recent call last):
  File "/workspaces/kanachan-wsl/kanachan/simulation/run.py", line 12, in <module>
    from kanachan.simulation import simulate
  File "/usr/local/lib/python3.10/dist-packages/kanachan/simulation/__init__.py", line 5, in <module>
    from ._simulation import simulate, test # pylint: disable=import-error
ImportError: libmarisa.so.0: cannot open shared object file: No such file or directory
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ export LD_LIBRARY_PATH=/root/.local/lib:$LD_LIBRARY_PATH
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ python kanachan/simulation/run.py 
Traceback (most recent call last):
  File "/workspaces/kanachan-wsl/kanachan/simulation/run.py", line 12, in <module>
    from kanachan.simulation import simulate
  File "/usr/local/lib/python3.10/dist-packages/kanachan/simulation/__init__.py", line 5, in <module>
    from ._simulation import simulate, test # pylint: disable=import-error
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/local/lib/python3.10/dist-packages/kanachan/simulation/_simulation.so)
```

**Comment by 0num4** [comment]
ええやん
```
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ strings /root/.local/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
GLIBCXX_3.4.31
GLIBCXX_3.4.32
GLIBCXX_TUNABLES
GLIBCXX_DEBUG_MESSAGE_LENGTH
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ export LD_LIBRARY_PATH=/root/.local/lib64:$LD_LIBRARY_PATH
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ python kanachan/simulation/run.py 
usage: run.py [-h] [--device DEV] [--dtype DTYPE] --baseline-model BASELINE_MODEL --baseline-grade BASELINE_GRADE --proposed-model PROPOSED_MODEL --proposed-grade PROPOSED_GRADE --room {bronze,silver,gold,jade,throne}
              [--dongfengzhan] [--mode {2vs2,1vs3}] [--non-duplicated] [-n N] [--batch-size N_BATCH] [--concurrency N_THREADS]
run.py: error: the following arguments are required: --baseline-model, --baseline-grade, --proposed-model, --proposed-grade, --room
```

**Comment by 0num4** [comment]
run.pyを走らせることはできたが、cppのsimulateを呼び出すときにGILが解放できてないみたいなエラーが出る…
```
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ python kanachan/simulation/run.py --baseline-model ./outputs/2024-01-07/11-19-44/
.hydra/      snapshots/   tensorboard/ train.log    
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ python kanachan/simulation/run.py --baseline-model ./outputs/2024-01-07/11-19-44/snapshots/model.kanachan --baseline-grade 8 --proposed_grade 9 --room gold
usage: run.py [-h] [--device DEV] [--dtype DTYPE] --baseline-model BASELINE_MODEL --baseline-grade BASELINE_GRADE --proposed-model PROPOSED_MODEL --proposed-grade PROPOSED_GRADE --room {bronze,silver,gold,jade,throne}
              [--dongfengzhan] [--mode {2vs2,1vs3}] [--non-duplicated] [-n N] [--batch-size N_BATCH] [--concurrency N_THREADS]
run.py: error: the following arguments are required: --proposed-model, --proposed-grade
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ python kanachan/simulation/run.py --baseline-model ./outputs/2024-01-07/11-19-44/snapshots/model.kanachan --proposed-model ./outputs/2024-01-07/11-19-44/snapshots/model.kanachan --b
aseline-grade 8 --proposed_grade 9 --room gold
usage: run.py [-h] [--device DEV] [--dtype DTYPE] --baseline-model BASELINE_MODEL --baseline-grade BASELINE_GRADE --proposed-model PROPOSED_MODEL --proposed-grade PROPOSED_GRADE --room {bronze,silver,gold,jade,throne}
              [--dongfengzhan] [--mode {2vs2,1vs3}] [--non-duplicated] [-n N] [--batch-size N_BATCH] [--concurrency N_THREADS]
run.py: error: the following arguments are required: --proposed-grade
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ python kanachan/simulation/run.py --baseline-model ./outputs/2024-01-07/11-19-44/snapshots/model.kanachan --proposed-model ./outputs/2024-01-07/11-19-44/snapshots/model.kanachan --baseline-grade 8 --proposed-grade 9 --room gold
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized

Thread 0x00007f65c5b12000 (most recent call first):
  File "/workspaces/kanachan-wsl/kanachan/simulation/run.py", line 131 in _main
  File "/workspaces/kanachan-wsl/kanachan/simulation/run.py", line 321 in <module>
Aborted
```

**Comment by 0num4** [comment]
元々localで動かしている原因としてはdockerが動かないから
https://github.com/Cryolite/kanachan/blob/fd1303377be509b3c430eb1c66e2037f5e95d4c9/kanachan/simulation/README.md?plain=1#L49
```
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ docker build --pull -f kanachan/Dockerfile -t cryolite/kanachan .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  841.2MB
Step 1/21 : ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:22.08-py3
Step 2/21 : FROM $BASE_IMAGE
22.08-py3: Pulling from nvidia/pytorch
Digest: sha256:1aa83e1a13f756f31dabf82bc5a3c4f30ba423847cb230ce8c515f3add88b262
Status: Image is up to date for nvcr.io/nvidia/pytorch:22.08-py3
 ---> b3d16c039217
Step 3/21 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> 3689ad431fd8
Step 4/21 : RUN set -euxo pipefail;     apt-get -y update;     apt-get -y dist-upgrade;     apt-get -y install       libssl-dev       locales       locales-all       python3-dev       python3-venv;     apt-get clean && rm -rf /var/lib/apt/lists/*;     locale-gen en_US.UTF-8 ja_JP.UTF-8;     useradd -ms /bin/bash ubuntu;     chown ubuntu:ubuntu /workspace
 ---> Using cache
 ---> 817f7c0d7c85
Step 5/21 : USER ubuntu
 ---> Using cache
 ---> 6fda2d218e20
Step 6/21 : RUN set -euxo pipefail;     python3 -m venv --system-site-packages "$HOME/.local";     . "$HOME/.local/bin/activate";     python3 -m pip install -U pip;     pushd /workspace;     git clone 'https://github.com/NVIDIA/apex.git';     pushd apex;     MAX_JOBS=$(($(nproc) / 2)) python3 -m pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./;     popd;     rm -rf apex;     popd
 ---> Running in 7e9819baa537
+ python3 -m venv --system-site-packages /home/ubuntu/.local
+ . /home/ubuntu/.local/bin/activate
++ deactivate nondestructive
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
++ '[' -n '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/home/ubuntu/.local
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/opt/conda/lib/python3.8/site-packages/torch_tensorrt/bin:/opt/conda/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ucx/bin:/opt/tensorrt/bin
++ PATH=/home/ubuntu/.local/bin:/opt/conda/lib/python3.8/site-packages/torch_tensorrt/bin:/opt/conda/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/ucx/bin:/opt/tensorrt/bin
++ export PATH
++ '[' -n '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' 'x(.local) ' '!=' x ']'
++ PS1='(.local) '
++ export PS1
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
+ python3 -m pip install -U pip
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: pip in /home/ubuntu/.local/lib/python3.8/site-packages (22.0.4)
Collecting pip
  Downloading pip-23.3.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 1.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-23.3.2
+ pushd /workspace
+ git clone https://github.com/NVIDIA/apex.git
/workspace /workspace
Cloning into 'apex'...
+ pushd apex
/workspace/apex /workspace /workspace
++ nproc
+ MAX_JOBS=8
+ python3 -m pip install -v --no-cache-dir --global-option=--cpp_ext --global-option=--cuda_ext ./
Using pip 23.3.2 from /home/ubuntu/.local/lib/python3.8/site-packages/pip (python 3.8)
DEPRECATION: --build-option and --global-option are deprecated. pip 24.0 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11859
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option.
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing /workspace/apex
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://pypi.ngc.nvidia.com
  Collecting setuptools
    Downloading setuptools-69.0.3.tar.gz (2.2 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 883.2 kB/s eta 0:00:00
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Installing backend dependencies: started
    Installing backend dependencies: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting wheel
    Downloading wheel-0.42.0.tar.gz (98 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 756.6 kB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: setuptools, wheel
    Building wheel for setuptools (pyproject.toml): started
    Building wheel for setuptools (pyproject.toml): finished with status 'done'
    Created wheel for setuptools: filename=setuptools-69.0.3-py3-none-any.whl size=819530 sha256=a55f9c59db8c9a67305a0ea4700eff555bebdc07d562cf7fbdf1f661e7ebce72
    Stored in directory: /tmp/pip-ephem-wheel-cache-o6wdmeah/wheels/2a/a4/bc/95d70bb60f249d3d19970aca05de0b89d334e4abfc6e0098f4
    Building wheel for wheel (pyproject.toml): started
    Building wheel for wheel (pyproject.toml): finished with status 'done'
    Created wheel for wheel: filename=wheel-0.42.0-py3-none-any.whl size=65375 sha256=177f9c9b0d45c47873b619f5b650346d632cdc35fb5e4d25058e09c9e581433d
    Stored in directory: /tmp/pip-ephem-wheel-cache-o6wdmeah/wheels/56/33/b4/401cfa0b66782c7e643824b24bb81ce0b34bc3a5b16cfe192e
  Successfully built setuptools wheel
  Installing collected packages: wheel, setuptools
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  numba 0.56.0 requires llvmlite<0.40,>=0.39.0dev0, but you have llvmlite 0.36.0 which is incompatible.
  tensorboard 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.1 which is incompatible.
  Successfully installed setuptools-69.0.3 wheel-0.42.0
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "/home/ubuntu/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/ubuntu/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ubuntu/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-5fry00s6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-5fry00s6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-5fry00s6/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 5, in <module>
  ModuleNotFoundError: No module named 'packaging'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/ubuntu/.local/bin/python3 /home/ubuntu/.local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpvy_9la3g
  cwd: /workspace/apex
  Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
The command '/bin/bash -c set -euxo pipefail;     python3 -m venv --system-site-packages "$HOME/.local";     . "$HOME/.local/bin/activate";     python3 -m pip install -U pip;     pushd /workspace;     git clone 'https://github.com/NVIDIA/apex.git';     pushd apex;     MAX_JOBS=$(($(nproc) / 2)) python3 -m pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./;     popd;     rm -rf apex;     popd' returned a non-zero code: 1
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ 
```

**Comment by 0num4** [comment]
```
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ export LD_LIBRARY_PATH=/root/.local/lib:$LD_LIBRARY_PATH
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ export LD_LIBRARY_PATH=/root/.local/lib64:$LD_LIBRARY_PATH
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ python kanachan/simulation/run.py --baseline-model ./outputs/2024-01-07/11-19-44/snapshots/model.kanachan --proposed-model ./outputs/2024-01-07/11-19-44/snapshots/model.kanachan --baseline-grade 8 --proposed-grade 9 --room gold --device cuda
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized

Thread 0x00007fc074bba000 (most recent call first):
  File "/workspaces/kanachan-wsl/kanachan/simulation/run.py", line 131 in _main
  File "/workspaces/kanachan-wsl/kanachan/simulation/run.py", line 321 in <module>
Aborted
```

pythonからc(cpp)で作られた*.so（共有ファイル）を呼び出す方法はnつある
* ctypes

https://hpc-phys.kek.jp/workshop/workshop211125/aoyama_211125.pdf
![image](https://github.com/0num4/kanachan/assets/49909750/3bbfc378-a3d8-4650-a079-52b95292aa18)

PyThreadState_Getについて
https://docs.python.org/ja/3/c-api/init.html?highlight=pythreadstate_get

これがわかりやすそう
https://cpp-learning.com/python_c_api_step1/

**Comment by 0num4** [comment]
cppのビルドはこの辺
```
# Build kanachan.
mkdir -p /workspaces/kanachan/build
pushd /workspaces/kanachan/build
CC="$HOME/.local/bin/gcc" CXX="$HOME/.local/bin/g++" cmake \
  -DSHANTEN_NUMBER_SOURCE_PATH=/workspaces/shanten-number \
  -DCMAKE_BUILD_TYPE=Release \
  ..
VERBOSE=1 make -j make_trie simulation
mkdir -p "$HOME/.local/share/kanachan"
src/xiangting/make_trie /workspaces/shanten-number "$HOME/.local/share/kanachan"
cp src/simulation/libsimulation.so ../kanachan/simulation/_simulation.so
popd
```

**Comment by 0num4** [comment]
なんか良く分からんけど動いた
```
docker build -f kanachan/Dockerfile --build-arg BASE_IMAGE=nvcr.io/nvidia/pytorch:23.03-py3 -t cryolite/kanachan .
```
![image](https://github.com/0num4/kanachan/assets/49909750/6da0571d-c138-4f2d-9578-8c779ab88853)

```
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ docker build --pull -f kanachan/simulation/Dockerfile -t cryolite/kanachan.simulation .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  841.2MB
Step 1/3 : FROM cryolite/kanachan
latest: Pulling from cryolite/kanachan
Digest: sha256:82b0fe786266769e0bd74386b56a20ffbd5d34db5fd293b12ce3d7587dd068aa
Status: Downloaded newer image for cryolite/kanachan:latest
 ---> 9c1c177aff9c
Step 2/3 : WORKDIR /workspace/data
 ---> Using cache
 ---> 30a672386676
Step 3/3 : ENTRYPOINT ["python3", "-m", "kanachan.simulation.run"]
 ---> Running in 0b42e508fa52
Removing intermediate container 0b42e508fa52
 ---> 8024c1d459fb
Successfully built 8024c1d459fb
Successfully tagged cryolite/kanachan.simulation:latest
```

**Comment by 0num4** [comment]
中に入りたい
```
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ docker run --gpus all -v /workspaces/kanachan-wsl/outputs/2024-01-07/11-19-44/:/workspace/data -it --rm cryolite/kanachan.simulation --baseline-model /workspace/data/snapshots/model.kanachan --p
roposed-model /workspaces/data/snapshots/model.kanachan --baseline-grade 8 --proposed-grade 9 --room gold
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kanachan/simulation/run.py", line 291, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kanachan/simulation/run.py", line 73, in main
    raise RuntimeError(f'{config.baseline_model}: Does not exist.')
RuntimeError: /workspace/data/snapshots/model.kanachan: Does not exist.
```

**Comment by 0num4** [comment]
docker run --gpus all -v /workspaces/kanachan-wsl/outputs/2024-01-07/11-19-44/:/workspace/data -it --rm cryolite/kanachan.simulation --baseline-model /workspace/data/snapshots/model.kanachan --proposed-model /workspaces/data/snapshots/model.kanachan --baseline-grade 8 --proposed-grade 9 --room gold

**Comment by 0num4** [comment]
```
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ docker build --pull -f kanachan/simulation/Dockerfile -t cryolite/kanachan.simulation .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  841.2MB
Step 1/4 : FROM cryolite/kanachan
latest: Pulling from cryolite/kanachan
Digest: sha256:82b0fe786266769e0bd74386b56a20ffbd5d34db5fd293b12ce3d7587dd068aa
Status: Image is up to date for cryolite/kanachan:latest
 ---> 9c1c177aff9c
Step 2/4 : COPY outputs/2024-01-07/11-19-44 /workspace/data/
 ---> e6e2e975055e
Step 3/4 : WORKDIR /workspace/data
 ---> Running in bed458fa6f24
Removing intermediate container bed458fa6f24
 ---> 1e492c0cde68
Step 4/4 : ENTRYPOINT ["/bin/bash"]
 ---> Running in 85f253bb479a
Removing intermediate container 85f253bb479a
 ---> f35435414fb1
Successfully built f35435414fb1
Successfully tagged cryolite/kanachan.simulation:latest
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ docker run --gpus all -it --rm cryolite/kanachan.simulation 
ubuntu@b5cd3b944649:/workspace/data$ ls
snapshots  tensorboard  train.log
ubuntu@b5cd3b944649:/workspace/data$ exit
exit
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ docker run --gpus all -it --rm cryolite/kanachan.simulation 
ubuntu@35a725ccc103:/workspace/data$ exit
exit
^[[Aroot ➜ /workspaces/kanachan-wsl (majsoul-proto) $ docker build --pull -f kanachan/simulation/Dockerfile -t cryolite/kanachan.simulation .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  841.2MB
Step 1/4 : FROM cryolite/kanachan
latest: Pulling from cryolite/kanachan
Digest: sha256:82b0fe786266769e0bd74386b56a20ffbd5d34db5fd293b12ce3d7587dd068aa
Status: Image is up to date for cryolite/kanachan:latest
 ---> 9c1c177aff9c
Step 2/4 : COPY outputs/2024-01-07/11-19-44 /workspace/data/
 ---> Using cache
 ---> e6e2e975055e
Step 3/4 : WORKDIR /workspace/data
 ---> Using cache
 ---> 1e492c0cde68
Step 4/4 : ENTRYPOINT ["python3", "-m", "kanachan.simulation.run"]
 ---> Running in 52f107816f59
Removing intermediate container 52f107816f59
 ---> c9a807a7d7da
Successfully built c9a807a7d7da
Successfully tagged cryolite/kanachan.simulation:latest
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ docker run --gpus all -it --rm cryolite/kanachan.simulation  --baseline-model snapshots/model.kanachan --proposed-model snapshots/model.kanachan --baseline-grade 8 --proposed-grade 9 --room gold
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kanachan/simulation/run.py", line 291, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kanachan/simulation/run.py", line 76, in main
    baseline_model = load_model(config.baseline_model)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/kanachan/training/bert/model_loader.py", line 251, in load_model
    config = yaml.load(f, Loader=yaml.Loader)
  File "/opt/conda/lib/python3.8/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/opt/conda/lib/python3.8/site-packages/yaml/loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "/opt/conda/lib/python3.8/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/opt/conda/lib/python3.8/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/opt/conda/lib/python3.8/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/opt/conda/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
root ➜ /workspaces/kanachan-wsl (majsoul-proto) $ 
```
dockerもファイルのエンコーディングがおかしいって言っている

**Comment by 0num4** [comment]
![image](https://github.com/0num4/kanachan/assets/49909750/aec4e1f0-c88d-42d9-81b5-54ef99395743)
ここで死んでんね

**Comment by 0num4** [comment]
_simulation.soだけビルドしてrun.pyから使う(これもこける)
```
cd build
src/xiangting/make_trie /workspaces/shanten-number
echo "$HOME"
# /root
CC="$HOME/.local/bin/gcc" CXX="$HOME/.local/bin/g++" cmake   -DSHANTEN_NUMBER_SOURCE_PATH=/workspaces/shanten-number   -DCMAKE_BUILD_TYPE=Release   ..
export LD_LIBRARY_PATH=/root/.local/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/root/.local/lib:$LD_LIBRARY_PATH
src/xiangting/make_trie /workspaces/shanten-number/ "$HOME/.local/share/kanachan"
cp src/simulation/libsimulation.so ../kanachan/simulation/_simulation.so
cd ../
cp build/src/simulation/libsimulation.so kanachan/simulation/_simulation.so
pip install .
python kanachan/simulation/run.py --baseline-model ./outputs/2024-01-07/11-19-44/snapshots/model.kanachan --proposed-model ./outputs/2024-01-07/11-19-44/snapshots/model.kanachan --baseline-grade 8 --proposed-grade 9 --room gold
```
